export default {
  headers: [
    { key: "num", value: "" },
    { key: "title", value: "Title" },
    { key: "author", value: "Author" },
    { key: "category", value: "Category" },
    { key: "update", value: "Update" },
    { key: "status", value: "Status" },
  ],
  headers_sort: [
    { key: "num", value: "", sortable: true },
    { key: "title", value: "Title" },
    { key: "author", value: "Author" },
    { key: "category", value: "Category" },
    { key: "update", value: "Update", sortable: true },
    { key: "status", value: "Status" },
  ],
  headers_search: [
    { key: "num", value: "" },
    { key: "title", value: "Title", search: true },
    { key: "author", value: "Author", search: true },
    { key: "category", value: "Category" },
    { key: "update", value: "Update" },
    { key: "status", value: "Status" },
  ],
  headers_filter: [
    { key: "num", value: "" },
    { key: "title", value: "Title" },
    { key: "author", value: "Author" },
    {
      key: "category",
      value: "Category",
      filtered: true,
      filterItems: ["Health", "Food", "Sport"],
    },
    { key: "update", value: "Update" },
    { key: "status", value: "Status" },
  ],
  rows: [
    {
      id: "a",
      num: 1,
      title: "Now in the supermarket and at the kiosk: the new Foodscout",
      author: "Foodscout team 1",
      category: "Health",
      update: "18/10/20",
      status: "Published",
    },
    {
      id: "b",
      num: 2,
      title: "Now in the supermarket and at the kiosk: the new Foodscout",
      author: "Foodscout team 2",
      category: "Food",
      update: "17/10/20",
      status: "Draft",
    },
    {
      id: "c",
      num: 3,
      title: "Now in the supermarket and at the kiosk: the new Foodscout",
      author: "Foodscout team 3",
      category: "Sport",
      update: "19/10/20",
      status: "Draft",
    },
  ],
};
